"""follow

Revision ID: 945d1a9e6dba
Revises: c027816ac901
Create Date: 2023-06-27 10:15:37.673501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "945d1a9e6dba"
down_revision = "c027816ac901"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follow",
        sa.Column("following_user_id", sa.Uuid(), nullable=False),
        sa.Column("followed_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("followed_user_id != following_user_id", name="ck_user_cannot_follow_self"),
        sa.ForeignKeyConstraint(["followed_user_id"], ["user.id"], name="fk_followed_user_id", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["following_user_id"], ["user.id"], name="fk_following_user_id", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("following_user_id", "followed_user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("follow")
    # ### end Alembic commands ###
